# Generated by Django 6.0.6 on 2026-06-04 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('match_score', models.IntegerField(default=0)),
                ('decision', models.CharField(choices=[('GO', '🟢 GO'), ('NO-GO', '🚨 NO-GO'), ('MARGINAL', '⚠️ MARGINAL')], default='MARGINAL', max_length=15)),
                ('report_markdown', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
